### ISSUE TITLE
Issue with requests and ssl

### ISSUE THREAD

**Issue by chatainsim** [rmarchant/gandi-ddns#15]
Hello,
I've got an error with, I think, requests, throwing me OpenSSL error:
```
2020-11-25 17:50:34.646715 - section local
https://dns.api.gandi.net/api/v5/domains/easter.fr/records/beta/A
Traceback (most recent call last):
  File "./gandi_ddns.py", line 131, in <module>
    main()
  File "./gandi_ddns.py", line 110, in main
    external_ip = get_ip(ipify_api, retries)
  File "./gandi_ddns.py", line 48, in get_ip
    return get_ip_inner(ipify_api)
  File "./gandi_ddns.py", line 25, in get_ip_inner
    r = requests.get(ipify_api, timeout=3)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/ssl_.py", line 321, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 428, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 776, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('PEM routines', 'get_header_and_data', 'short header'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'PEM lib')]
```

I had to add verify=False in every requests.get call.
Do you know how can I solve this ?

Thank you.

**Comment by rmarchant** [comment]
https://dns.api.gandi.net/ is no longer used. The script now uses https://api.gandi.net/v5/livedns/.
